# Generated by Django 4.1.5 on 2023-02-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0007_alter_game_home_score_prediction_alter_game_pmscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.CharField(default='2023-02-07', max_length=10),
        ),
    ]
