# Generated by Django 4.1.5 on 2023-02-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0008_alter_game_gamedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dk_home_spread',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='dk_visitor_spread',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
