# Generated by Django 4.1.5 on 2023-02-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0009_game_dk_home_spread_game_dk_visitor_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='home_games_loss',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_games_won',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='visitor_games_loss',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='visitor_games_won',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.CharField(default='2023-02-09', max_length=10),
        ),
    ]
