# Generated by Django 4.2.5 on 2023-10-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predict", "0010_game_home_games_loss_game_home_games_won_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="bet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="complexSpread",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="ev_margin1",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="ev_margin2",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="ev_margin3",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="ev_won",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="homeInjury",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="homeInjuryComplex",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="home_history",
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="home_last_game",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="home_streak",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="margin",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="model",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.AddField(
            model_name="game",
            name="removed_players",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="spread_prediction",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="visitorInjury",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="visitorInjuryComplex",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="visitor_history",
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="visitor_last_game",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="visitor_streak",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="gamedate",
            field=models.CharField(default="2023-10-23", max_length=10),
        ),
    ]
