# Generated by Django 4.2.5 on 2023-11-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predict", "0013_alter_game_gamedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="gamedate",
            field=models.CharField(default="2023-11-09", max_length=10),
        ),
    ]
