# Generated by Django 4.2.5 on 2023-11-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predict", "0016_tensorflowmodel_permagame"),
    ]

    operations = [
        migrations.AddField(
            model_name="tensorflowmodel",
            name="model_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
