# Generated by Django 4.2.5 on 2023-12-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predict", "0019_modelreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="home_history2",
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="visitor_history2",
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="gamedate",
            field=models.CharField(default="2023-12-02", max_length=10),
        ),
    ]
