# Generated by Django 4.2.5 on 2024-02-01 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("predict", "0020_game_home_history2_game_visitor_history2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="simpleRecord",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="game",
            name="gamedate",
            field=models.CharField(default="2024-02-01", max_length=10),
        ),
        migrations.CreateModel(
            name="ArbLoad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
