# Generated by Django 4.2.5 on 2024-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0021_game_simplerecord_alter_game_gamedate_arbload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamedate',
            field=models.CharField(default='2024-11-21', max_length=10),
        ),
    ]
